Feature: Documentation site structure
  As a ratchet user
  I want a documentation website built from the repository's docs
  So that I can read ratchet's reference docs in a browser

  Background:
    Given the ratchet repository

  Scenario: A standalone Docusaurus app lives in website/
    Given the repository has no documentation site yet
    When the documentation site is scaffolded
    Then a Docusaurus app exists at "website/" with its own "package.json"
    And the app uses the "@docusaurus/preset-classic" preset
    And the app has no blog and no sample tutorial docs

  Scenario: The site sources reference content from the root docs/ directory
    Given a Docusaurus app at "website/"
    When its docs plugin is configured
    Then the docs plugin "path" resolves to "../docs"
    And the docs sidebar is autogenerated from the files under "../docs"
    And reference docs are served under the "/docs" route

  Scenario: The site root serves a landing page, not the docs
    Given the documentation site is built
    When a visitor opens the site root "/"
    Then they see the custom landing page
    And they do not see a reference doc at "/"
    And reference docs remain served under "/docs"
