// Unit test for the Docusaurus sidebars config (`website/sidebars.ts`).
//
// `sidebars.ts` is a pure configuration module with no runtime dependencies: it
// exports a single `SidebarsConfig` object. Importing the default export and
// asserting its shape exercises the module's lines and locks in the contract the
// docs site relies on (one autogenerated sidebar rooted at the docs directory).

import { describe, it, expect } from 'vitest';

import sidebars from '../../website/sidebars.ts';

describe('website/sidebars.ts', () => {
  it('exports a single autogenerated docsSidebar', () => {
    expect(sidebars).toBeTypeOf('object');
    expect(sidebars).toHaveProperty('docsSidebar');

    const docsSidebar = sidebars.docsSidebar;
    expect(Array.isArray(docsSidebar)).toBe(true);
    expect(docsSidebar).toHaveLength(1);
  });

  it('autogenerates the sidebar from the docs root directory', () => {
    const [entry] = sidebars.docsSidebar as Array<{ type: string; dirName: string }>;
    expect(entry).toMatchObject({ type: 'autogenerated', dirName: '.' });
  });
});
