Feature: Documentation content seed and references
  As a documentation maintainer
  I want the docs/ directory seeded and the project references updated
  So that the site has buildable content and users can find it

  Background:
    Given the ratchet repository

  Scenario: The root docs/ directory is seeded with an intro page
    Given the repository has no "docs/" directory yet
    When the documentation change is applied
    Then a "docs/" directory exists at the repository root
    And it contains an "intro.md" reference page
    And the autogenerated sidebar shows the intro entry

  Scenario: The website build and deployment are documented as reference
    Given the website package exists at "website/"
    When "website/README.md" is read
    Then it documents local development, build, and Cloudflare Pages settings for the site
    And the documentation follows the project documentation standard

  Scenario: The project README points readers to the documentation site
    Given the documentation site exists
    When the repository "README.md" is read
    Then it links to the documentation site
