import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * A single autogenerated sidebar: every file added under the root `docs/`
 * directory appears automatically, so no sidebar maintenance is needed as the
 * documentation content grows.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
